services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: minierp-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MiniERP@123"
    ports:
      - "1433:1433"

  api:
    image: minierp-api
    container_name: minierp-api
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MiniERPDb;User Id=sa;Password=MiniERP@123;TrustServerCertificate=True;"